version: "3.5"
services:
  node-primary:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
    container_name: node-primary
    environment:
      - xpack.security.enabled=false
      - discovery.seed_hosts=node-primary,node-secondary,monitoring
      - cluster.initial_master_nodes=172.25.0.2
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet
  node-secondary:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
    container_name: node-secondary
    environment:
      - discovery.seed_hosts=node-primary,node-secondary,monitoring
      - cluster.initial_master_nodes=172.25.0.2
      - xpack.security.enabled=false
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - 9300:9200
    networks:
      - esnet
    #profiles:
    #  - donotstart
  monitoring:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.1
    container_name: monitoring
    environment:
      - discovery.seed_hosts=node-primary,node-secondary,monitoring
      - cluster.initial_master_nodes=172.25.0.2
      - xpack.security.enabled=false
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    ports:
      - 9400:9200
    networks:
      - esnet
    #profiles:
    #  - donotstart
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local
networks:
  esnet:
